// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujqONw1tcJGG6YtTpyb_iedPAe8hN9pw',
    appId: '1:1084451795566:web:4c62ec1fe1049cfde56c7f',
    messagingSenderId: '1084451795566',
    projectId: 'omnisell-crm',
    authDomain: 'omnisell-crm.firebaseapp.com',
    storageBucket: 'omnisell-crm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnmuX1Eo9czU7ZKY4VKCtalA4YobE37lM',
    appId: '1:1084451795566:android:7601792dc8962b4fe56c7f',
    messagingSenderId: '1084451795566',
    projectId: 'omnisell-crm',
    storageBucket: 'omnisell-crm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVPg0zAxmDeoQqj0Gjmm6mjXgpyqjc4SI',
    appId: '1:1084451795566:ios:0a083f027e32b48ee56c7f',
    messagingSenderId: '1084451795566',
    projectId: 'omnisell-crm',
    storageBucket: 'omnisell-crm.appspot.com',
    iosBundleId: 'com.omnisellworksportal.omnisellWorksportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVPg0zAxmDeoQqj0Gjmm6mjXgpyqjc4SI',
    appId: '1:1084451795566:ios:0a083f027e32b48ee56c7f',
    messagingSenderId: '1084451795566',
    projectId: 'omnisell-crm',
    storageBucket: 'omnisell-crm.appspot.com',
    iosBundleId: 'com.omnisellworksportal.omnisellWorksportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBujqONw1tcJGG6YtTpyb_iedPAe8hN9pw',
    appId: '1:1084451795566:web:fcab606818137c01e56c7f',
    messagingSenderId: '1084451795566',
    projectId: 'omnisell-crm',
    authDomain: 'omnisell-crm.firebaseapp.com',
    storageBucket: 'omnisell-crm.appspot.com',
  );
}
